package agenda;

import java.awt.Dimension;
import java.awt.Toolkit;

public class JAdmDeletar extends javax.swing.JFrame {

  
    public JAdmDeletar() {
        initComponents();
    }

    private int tipo_del = 1; //tipo del = 1 CPF, = 2 RG, = 3 por nome;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG_del = new javax.swing.ButtonGroup();
        JB_voltar1 = new javax.swing.JButton();
        JL_title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JR_CPF = new javax.swing.JRadioButton();
        JF_nome = new javax.swing.JTextField();
        JF_nome1 = new javax.swing.JTextField();
        JR_RG = new javax.swing.JRadioButton();
        JR_nome = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        BG_del.add(JR_nome);
        BG_del.add(JR_RG);
        BG_del.add(JR_CPF);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JB_voltar1.setText("Voltar");
        JB_voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_voltar1ActionPerformed(evt);
            }
        });

        JL_title.setFont(new java.awt.Font("Traditional Arabic", 2, 36)); // NOI18N
        JL_title.setForeground(new java.awt.Color(204, 0, 51));
        JL_title.setText("Deletar Pessoa ou Conta");

        jLabel1.setText("Deletar pessoa por:");

        JR_CPF.setSelected(true);
        JR_CPF.setText("CPF");
        JR_CPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JR_CPFActionPerformed(evt);
            }
        });

        JR_RG.setText("RG");
        JR_RG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JR_RGActionPerformed(evt);
            }
        });

        JR_nome.setText("Nome");
        JR_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JR_nomeActionPerformed(evt);
            }
        });

        jButton1.setText("Deletar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Deletar conta:");

        jLabel3.setText("ID:");

        jButton3.setText("Deletar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JF_nome)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JF_nome1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JL_title)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JR_CPF)
                                .addGap(18, 18, 18)
                                .addComponent(JR_RG)
                                .addGap(18, 18, 18)
                                .addComponent(JR_nome))
                            .addComponent(jLabel1)
                            .addComponent(JB_voltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL_title)
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JR_CPF)
                    .addComponent(JR_RG)
                    .addComponent(JR_nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JF_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JF_nome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(JB_voltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_voltar1ActionPerformed
        JAdministrador jad = new JAdministrador();
        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
        jad.setLocation((tela.width - jad.getSize().width)/2,(tela.height - jad.getSize().height)/2);
        jad.show();
        this.dispose();
    }//GEN-LAST:event_JB_voltar1ActionPerformed

    private void JR_CPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JR_CPFActionPerformed
        tipo_del = 1;
    }//GEN-LAST:event_JR_CPFActionPerformed

    private void JR_RGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JR_RGActionPerformed
        tipo_del = 2;
    }//GEN-LAST:event_JR_RGActionPerformed

    private void JR_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JR_nomeActionPerformed
        tipo_del = 3;
    }//GEN-LAST:event_JR_nomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //Realizar o delete por cpf, rg ou nome da pessoa;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       //Realizar o delete por ID da conta;
    }//GEN-LAST:event_jButton3ActionPerformed

    public static void main(String args[]) {
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAdmDeletar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BG_del;
    private javax.swing.JButton JB_voltar1;
    private javax.swing.JTextField JF_nome;
    private javax.swing.JTextField JF_nome1;
    private javax.swing.JLabel JL_title;
    private javax.swing.JRadioButton JR_CPF;
    private javax.swing.JRadioButton JR_RG;
    private javax.swing.JRadioButton JR_nome;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
